#!/bin/bash
#This is a daemon file it monitors filesystem which you mention in fsmond.conf

source /usr/bin/fsyntax

#echo "$i = $y"
#echo "$x = $z"

adir=$((i+y))
aid=$((x+z))

#echo "$adir"
#echo "$aid"

exec 3>&1 4>&2
trap 'exec 2>&4 1>&3' 0 1 2 3


########### auto_run function starts here to delete or move old files ##############

        function auto_run () {

          while read line
          do
	    d="$(echo $line | awk '{print $1}')"
  	    min="$(echo $line | awk '{print $2}')"
  	    max="$(echo $line | awk '{print $3}')"
  	    mov="$(echo $line | awk '{print $4}')"

            us="$(df -h $d | tail -n1 | grep "/" | awk '{print $(NF-1)}')"
            us=${us%?}
            #echo "$us"

            #echo "$min"

            #echo "$max"
	    
	    #echo "$mov"
	    
	    if [ ! -z "$mov" ]
	    then
		#echo "auto_mov"
	        auto_mov
	    else
            #Here we are calling auto_del_1 fun to auto deletion of old files
            #echo "auto_del"
	    auto_del
	    fi
          done < /usr/bin/fs_man

        }

########### auto_run function ends here #############################

###########**************################**************##############

########### auto_mov function starts here to move files ############# 

	function auto_mov () {

         #echo "$d $min $max $us"

          if [ $us -gt $max ]
          then

            while [ $us -gt $min ]
            do

              old=$(find $d -printf '%T+ %p\n' | sort | head -n 1 | awk '{print $NF}')

              #echo "$old"
	      mv $old $mov
                 
              us="$(df -h $d | tail -n1 | grep "/" | awk '{print $(NF-1)}')"
	      us=${us%?}
            done


          fi

        }

############ auto_mov funtion ends here #############################

###########*************################**************###############

############ auto_del function starts here to delete files ##########

	function auto_del () {

         #echo "$d $min $max $us"

          if [ $us -gt $max ]
          then

            while [ $us -gt $min ]
            do

              old=$(find $d -printf '%T+ %p\n' | sort | head -n 1 | awk '{print $NF}')

              #echo "$old"
	      rm -rf $old

              us="$(df -h $d | tail -n1 | grep "/" | awk '{print $(NF-1)}')"
	      us=${us%?}
            done


          fi

        }

############ auto_del function ends here ############################

################***************###############*************##########

############ auto_mail function starts here to send a mail ##########

	function auto_mail () {
	
	while read line
          do
	    d="$(echo $line | awk '{print $1}')"
  	    thsd="$(echo $line | awk '{print $2}')"
  	    emx="$(echo $line | awk '{print $3}')"
            
	    ind="$(df -h $d | tail -n1 | grep "/" | awk '{print $(NF-1)}')"
            ind=${ind%?}
            #echo "$ind"
	    
	    
            #echo "$thsd"
	    
            #echo "$emx"
	    r="$(cat /etc/flag | grep $d | awk '{print $NF; exit}')" 
	    #echo "$r" 
	    if [ $r -eq 0 ]
	    then 
	      if [ $ind -ge $thsd ]
	      then
		echo "$(df -h $d)" | mail -s "filesystem status" $emx	
		sed -i -e "s#$d 0#$d 1#g" /etc/flag 
		#echo "nothing"
		
	      fi
	
	    elif [ $ind -ge 99 ]
	    then
	     #echo "filesystem almost full "
	     echo "[$(date +"%d-%m-%Y-%H:%M:%S")] Filesystem is Almost Full $ind%" >> /var/log/fsmond.log 
	     echo "$(df -h $d)" | mail -s "filesystem status" $emx
	     	      
	    fi
           
	 
          done < /usr/bin/fs_mon

        }

############# auto_mail function ends here ###########################

#############***************#############*************################

###############################

if ( [[ $adir = 0 ]] ) && ( [[ $z -eq $x ]] )
then
     echo "auto_mail"
     while true
     do
	auto_mail
     done

elif ( [[ $aid = 0 ]] ) && ( [[ $y -eq $i ]] )
then
     echo "auto_run"
     while true
     do
	auto_run
     done
	
elif [ $z -eq $x -a $y -eq $i ]
then	
	#echo "auto_mail & auto_run"
	#auto_mail
       #auto_run

	while true
        do
          auto_mail
          auto_run
        done

fi

##############################



#################********* Script End *************##################
