#!/bin/bash
#This is a service file for fsmond daemon 

function auto_start () {

	source /usr/bin/fsyntax

        if [ -z "$fail" ]
        then
            nohup /usr/bin/fsmond > /dev/null 2>&1 & echo $! > /var/run/fsmond.pid
            echo "Starting fsmond [   OK   ]"
        else

            echo "Starting fsmond : $fail [ Failed ]"
        fi

}



case "$1" in
start)
	pid=/var/run/fsmond.pid

	if [ -f "$pid" ]
	then
    	    process="$(ps -ef | grep "/usr/bin/fsmond" | egrep -v "grep")"
    	    if [ -z "$process" ]
    	    then
		rm -rf /var/run/fsmond.pid
		auto_start
    	    else
        	echo "fsmond already running pid ( $(cat $pid) )"
    	    fi
	else
    	    process="$(ps -ef | grep "/usr/bin/fsmond" | egrep -v "grep")"
    	    if [ -z "$process" ]
    	    then
        	auto_start
     	    else
        	pi="$(ps -ef | grep "/usr/bin/fsmond" | egrep -v "grep" | awk '{print $2}')"
		echo "$pi" > /var/run/fsmond.pid
        	echo "fsmond already running ( $pi )"
    	    fi

	fi
	
	;;
stop)
	 pid=/var/run/fsmond.pid
        if [ -f "$pid" ]
        then
            pi="$(echo "$(cat $pid)")"
            process="$(ps -ef | grep "/usr/bin/fsmond" | egrep -v "grep")"
            if [ -z "$process" ]
            then
                rm -rf /var/run/fsmond.pid
                echo "Stopping fsmond [   OK   ]"

            else
                kill -9 $pi
                rm -rf /var/run/fsmond.pid
                echo "Stopping fsmond [   OK   ]"
            fi
        else
            process="$(ps -ef | grep "/usr/bin/fsmond" | egrep -v "grep")"
            if [ -z "$process" ]
            then
                echo "Stopping...... [ Failed ]"
            else
                pi="$(ps -ef | grep "/usr/bin/fsmond" | egrep -v "grep" | awk '{print $2}')"
                kill -9 $pi
                echo "Stopping fsmond [   OK   ]"
            fi
        fi

	;;
restart)
	$0 stop
	$0 start
	;;
status)
	pid=/var/run/fsmond.pid
	if [ -f "$pid" ]
        then
                echo "fsmond is running, pid ( $(cat $pid) )"
        else
                echo fsmond is NOT running
                exit 1
        fi

	;;
*)
	echo "Usage: $0 {start | stop | status | restart}"
esac

exit 0
