#!/bin/bash

#This file checks the syntax before launching the daemon and give corresponding output.

########### Information Gathering from configuration file ###################

fsid="$(cat /etc/fsmond.conf | grep "fsid" | egrep -v "#" | awk '{print $3}')"
#echo "$fsid"

if [ -z "$fsid" ]
then
    z=0
else
z="$(echo "$fsid" | wc -l)"
#echo "$z"
fi

x=0
p=0

dir="$(cat /etc/fsmond.conf | grep "ldir" | egrep -v "#" | awk '{print $3}')"
#echo "$dir"

if [ -z "$dir" ]
then
    y=0
else
y="$(echo "$dir" | wc -l)"
#echo "$y"
fi

re='^[0-9]+$'
i=0

echo "" > /etc/flag
for j in $fsid
do
echo "$j $p" >> /etc/flag

done

cat /etc/fsmond.conf | grep "ldir" | egrep -v "#" | awk '{print $3,$6,$9,$12}' > /usr/bin/fs_man
cat /etc/fsmond.conf | grep "fsid" | egrep -v "#" | awk '{print $3,$6,$9}' > /usr/bin/fs_mon

############### End of Information gathering ###########################

############### Loop starts for checking syntax of email ID ###########
while read line
do
  
  d="$(echo $line | awk '{print $1}')"
  ts="$(echo $line | awk '{print $2}')"
  email="$(echo $line | awk '{print $3}')"

        b=$(df -h $d 2>&1 1> /dev/null )
        if [ -z "$d" -o ! -z "$b" ]
        then
          fail="$(echo "Directory $j is invalid ")"
	  
	  echo "[$(date +"%d-%m-%Y-%H:%M:%S")] Directory $d is invalid " >> /var/log/fsmond.log
          break;
        else
          if [ -z "$ts" ]
          then
            fail="$(echo "Value should not be null")"
           
	    echo "[$(date +"%d-%m-%Y-%H:%M:%S")] Value should not be null" >> /var/log/fsmond.log
            break;

          else
            if ! [[ $ts =~ $re ]]
            then
              fail="$(echo "Threshold must be integer $ts")"

              echo "[$(date +"%d-%m-%Y-%H:%M:%S")] threshold must be integer $ts" >> /var/log/fsmond.log
              break;

            elif [ "$ts" -gt 99 ]
            then
              fail="$(echo "Threshold must be less than 99% ts = $ts")" 

              echo "[$(date +"%d-%m-%Y-%H:%M:%S")] Threshold must be less than 99% ts = $ts" >> /var/log/fsmond.log
              break;
            elif ! [[ "$email" == ?*@?*.?* ]]
            then
              fail="$(echo "Email id must be valid $email")"

              echo "[$(date +"%d-%m-%Y-%H:%M:%S")] Email id must be valid $email" >> /var/log/fsmond.log
              break;
            else
              x=$((x+1))
              #echo "$x"
            fi
          fi
      fi

done < /usr/bin/fs_mon

########### Syntax checking of email ID Loop ends here ##############

###################**************##################*********#########

########### Loop starts for checking syntax of Directorys and Threshold values ############

############### Loop starts for checking syntax of email ID ###########
while read line
do

  d="$(echo $line | awk '{print $1}')"
  min="$(echo $line | awk '{print $2}')"
  max="$(echo $line | awk '{print $3}')"
  mov="$(echo $line | awk '{print $4}')"

	movdir=$(df -h $mv 2>&1 1> /dev/null )

        a=$(df -h $d 2>&1 1> /dev/null )
        if ( [ -z "$d" -o ! -z "$a" ] ) || ( [ ! -z "$movdir" ] )
        then
          fail="$(echo "Directory $d or $mov is invalid")"
 	  #echo "$fail"
          echo "[$(date +"%d-%m-%Y-%H:%M:%S")] Directory $d or $movdir is invalid " >> /var/log/fsmond.log
          break;
	elif [ "$d" == "$mov" ]
	then
	     fail="$(echo "Source and target directories must be different (source = $d) (target = $mov) ")"
             echo "$fail"
             echo "[$(date +"%d-%m-%Y-%H:%M:%S")] Source and target directories must be different (source = $d) (target = $mov) " >> /var/log/fsmond.log
             break;

        else
          
          if [ -z "$min" -o -z "$max" ]
          then
            fail="$(echo "Value should not be null")" 

            echo "[$(date +"%d-%m-%Y-%H:%M:%S")] Value should not be null" >> /var/log/fsmond.log
            break;

          else
            if (! [[ $min =~ $re ]] ) || (! [[ $max =~ $re ]] )
            then
              fail="$(echo "Invalid value Min $min --- Max $max")"
	      #echo "$fail"
              echo "[$(date +"%d-%m-%Y-%H:%M:%S")] Invalid value Min $min --- Max $max" >> /var/log/fsmond.log
              break;

            elif ( [ "$min" -gt 99 -o "$max" -gt 100 ] ) || ( [ "$min" -gt "$max" ] )
            then
              fail="$(echo "Min should be less than Max [ min = $min ] and [ max = $max]")"

              echo "[$(date +"%d-%m-%Y-%H:%M:%S")] Min should be less than Max [ min = $min ] and [ max = $max]" >> /var/log/fsmond.log
              break;
            else
              i=$((i+1))
              #echo "$i"
            fi
          fi

        fi
   done < /usr/bin/fs_man


############ Syntax checking of Directorys and Threshold values Loop ends here ############

############************################***************##############

#echo "$i = $y"
#echo "$x = $z"

adir=$((i+y))
aid=$((x+z))

#echo "$adir"
#echo "$aid"


###############################

if [ $adir -eq 0 -a $aid -eq 0 ]
then
    fail="$(echo "configuration is empty daemon could not start")"
    

fi

#echo "$fail"
##############################



#################********* Script End *************##################
